// <auto-generated />
using System;
using Batch_input_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Batch_input_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261006064005_Add_runtime")]
    partial class Add_runtime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Batch_input_API.Models.BatchInputHistory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Machine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Msnv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RUNTIME")
                        .HasColumnType("datetime2");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TerminalID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isComplate")
                        .HasColumnType("bit");

                    b.Property<bool>("isDelete")
                        .HasColumnType("bit");

                    b.Property<int>("numRetry")
                        .HasColumnType("int");

                    b.Property<bool>("start")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("F2_BatchInput_History", (string)null);
                });

            modelBuilder.Entity("Batch_input_API.Models.ListPO", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DescriptionPO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDGroup")
                        .HasColumnType("int");

                    b.Property<string>("Po")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isComplate")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("IDGroup");

                    b.ToTable("F2_BatchInput_ListPO", (string)null);
                });

            modelBuilder.Entity("Batch_input_API.Models.ListPO", b =>
                {
                    b.HasOne("Batch_input_API.Models.BatchInputHistory", "BatchInputHistory")
                        .WithMany("ListPOs")
                        .HasForeignKey("IDGroup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BatchInputHistory");
                });

            modelBuilder.Entity("Batch_input_API.Models.BatchInputHistory", b =>
                {
                    b.Navigation("ListPOs");
                });
#pragma warning restore 612, 618
        }
    }
}
